name: Generate Tests

on:
  repository_dispatch:
    types: [generate-tests]

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - name: Print success message
        run: echo "✅ Repo B triggered successfully from PR"
